# Generated by Django 3.1.8 on 2021-06-02 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroes',
            name='catch_phrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
